.PHONY: up down logs migrate revision seed test shell reset up-dev

up:
	DOCKER_UID=$${SUDO_UID:-$$(id -u)} DOCKER_GID=$${SUDO_GID:-$$(id -g)} docker compose up -d --build

down:
	docker compose down

logs:
	docker compose logs -f

migrate:
	docker compose exec fastapi alembic upgrade head

# Author a new migration from any model changes since the last one. Autogenerate
# skips writing a file entirely if there's no actual schema diff (see env.py's
# process_revision_directives) - safe to run even when nothing changed.
# Usage: make revision name="add sessions table"
revision:
	docker compose exec fastapi alembic revision --autogenerate -m "$(if $(name),$(name),autogenerated changes)"

seed:
	docker compose exec fastapi python scripts/seed.py

test:
	docker compose exec fastapi pytest

shell:
	docker compose exec fastapi bash

reset:
	docker compose down -v

# reset -> up -> apply existing migrations -> author+apply any new ones your model
# changes introduced -> seed. The double migrate is deliberate: the first brings the
# DB to the last committed schema so revision has something correct to diff against;
# the second applies whatever revision just authored (a no-op if nothing changed).
up-dev:
	$(MAKE) reset
	$(MAKE) up
	$(MAKE) migrate
	$(MAKE) revision
	$(MAKE) migrate
	$(MAKE) seed
