"""add jira_site_url to team_members

Revision ID: b854487bcb15
Revises: 21c775806b64
Create Date: 2026-07-20 06:47:06.544096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b854487bcb15"
down_revision: str | Sequence[str] | None = "21c775806b64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_members", sa.Column("jira_site_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_members", "jira_site_url")
    # ### end Alembic commands ###
