"""add team_members table

Revision ID: b29ec002714c
Revises: 650a0f64e7dc
Create Date: 2026-07-20 04:26:49.773538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b29ec002714c"
down_revision: str | Sequence[str] | None = "650a0f64e7dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("azure_upn", sa.String(), nullable=False),
        sa.Column("jira_account_email", sa.String(), nullable=False),
        sa.Column("github_login", sa.String(), nullable=False),
        sa.Column("jira_cloud_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("azure_upn"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_members")
    # ### end Alembic commands ###
