"""add team_members.jira_account_id

Revision ID: 333720564f2a
Revises: b854487bcb15
Create Date: 2026-07-20 23:46:47.177987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "333720564f2a"
down_revision: str | Sequence[str] | None = "b854487bcb15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_members", sa.Column("jira_account_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_members", "jira_account_id")
    # ### end Alembic commands ###
